### ISSUE TITLE
router causes TWO clicks in case of a non-layers link 

### ISSUE THREAD

**Issue by thomashandorf** [layerJS/layerJS#51]
if a link is pressed and the routers do not react to it (non-layers link) the router will retrigger the click event. 
However when other frameworks are listening to the click event they will be called twice in this way.

One way could be to use stopImmediatePropagation. This however ist not secure as it depends on layerjs being attached first.

The other way is not to retrigger the click event but work with setting window.location.href. Would that work or was there a reason for retriggering the event

**Comment by kennytordeur** [comment]
We can't do window.location.href solution. If an other framework or user code is listening to the click event, this event won't be triggerd if we do a window.location.href. That is why the event is retriggered if layerjs can not handle it.

A solution might be to add an attribute to layerjs links. This way we only listen to layerjs links. 
The downside is that users can not add click listeners to layerjs links, because there is no guarantee that these listeners will be triggered or if they will only be triggered 1 time.

**Comment by thomashandorf** [comment]
Can you try to preventDefault and NOT “stopPropagation” at first and then do a location.href at the end. do the location.href change in a setTimeout of 1ms to get behind all following listeners. That should always execute all click handlers but no activate the link handling by the browser. Then, the location href would  not trigger any click handlers anymore.
